### PR TITLE
chore(svg): Remove unnecessary code from svgs

### PR DESCRIPTION
**Pull request by talend-glorieux**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Docs have been added / updated

**What is the current behavior?** (You can also link to an open issue here)

The svgs are big.

**What is the new behavior?**

The svg are of reasonable size.

**Other information**:
Used https://github.com/svg/svgo to clean the svg images.

Here is the output of the script:

```shell
add.svg:
Done in 32 ms!
11.716 KiB - 98.2% = 0.206 KiB

add_dataset.svg:
Done in 36 ms!
11.326 KiB - 97.2% = 0.313 KiB

add_lookup.svg:
Done in 18 ms!
11.489 KiB - 95.5% = 0.519 KiB

arrow_down.svg:
Done in 18 ms!
11.119 KiB - 98.8% = 0.139 KiB

arrow_right.svg:
Done in 16 ms!
11.119 KiB - 98.8% = 0.138 KiB

arrow_up.svg:
Done in 15 ms!
11.119 KiB - 98.4% = 0.173 KiB

badge.svg:
Done in 20 ms!
11.309 KiB - 86.5% = 1.53 KiB

cluster.svg:
Done in 15 ms!
0.751 KiB - 43% = 0.428 KiB

copy_dataset.svg:
Done in 15 ms!
11.713 KiB - 97.6% = 0.284 KiB

dataprep.svg:
Done in 17 ms!
12.22 KiB - 93.5% = 0.794 KiB

datastore.svg:
Done in 16 ms!
0.938 KiB + 8.2% = 1.015 KiB

delete.svg:
Done in 5 ms!
11.296 KiB - 96.3% = 0.417 KiB

edit.svg:
Done in 4 ms!
11.385 KiB - 96.8% = 0.361 KiB

edit_cancel.svg:
Done in 6 ms!
11.119 KiB - 94.8% = 0.575 KiB

edit_confirm.svg:
Done in 5 ms!
11.119 KiB - 96.1% = 0.436 KiB

edit_properties.svg:
Done in 9 ms!
13.948 KiB - 93.8% = 0.858 KiB

favorite.svg:
Done in 7 ms!
11.119 KiB - 97.8% = 0.24 KiB

feedback.svg:
Done in 9 ms!
11.698 KiB - 96.6% = 0.396 KiB

filter.svg:
Done in 4 ms!
11.508 KiB - 96% = 0.466 KiB

folder.svg:
Done in 6 ms!
11.104 KiB - 98.4% = 0.182 KiB

group.svg:
Done in 8 ms!
14.739 KiB - 89% = 1.614 KiB

help_center.svg:
Done in 7 ms!
14.035 KiB - 93.3% = 0.937 KiB

move_dataset.svg:
Done in 4 ms!
11.695 KiB - 97.6% = 0.282 KiB

onboarding.svg:
Done in 5 ms!
11.614 KiB - 89.2% = 1.253 KiB

parameters.svg:
Done in 3 ms!
11.119 KiB - 93.6% = 0.712 KiB

redo.svg:
Done in 3 ms!
11.713 KiB - 97.3% = 0.32 KiB

reset_filters.svg:
Done in 4 ms!
11.646 KiB - 94.4% = 0.651 KiB

search.svg:
Done in 6 ms!
11.718 KiB - 94.7% = 0.62 KiB

share.svg:
Done in 5 ms!
13.696 KiB - 95.4% = 0.628 KiB

streams.svg:
Done in 3 ms!
0.629 KiB - 7.5% = 0.582 KiB

undo.svg:
Done in 3 ms!
11.713 KiB - 97.2% = 0.326 KiB

user.svg:
Done in 5 ms!
14.126 KiB - 92.8% = 1.023 KiB
```

### CODE REVIEW

**Comment by jmfrancois** [comment]
@acateland the class and id are not really explicit (cls-1) ...
This is the result of the same 'script' used to build the document.
I think this has to be discussed with UX guys first

**Comment by acateland** [comment]
agreed

**Comment by talend-glorieux** [comment]
Yep I agree that we need some kind of reference to the element. The cleansing details can be customized.

**Comment by talend-glorieux** [comment]
Oups wrong click :(

**Comment by acateland** [comment]
who is responsible for cleaning svg

**Comment by talend-glorieux** [comment]
I would like to automate the cleaning process :)

**Pull request merged**
