### PR TITLE
feat: add talend logo

### PR DESCRIPTION
**Pull request by jmfrancois**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [x] Docs have been added / updated

**What is the current behavior?** (You can also link to an open issue here)

the talend logo is not here.

**What is the new behavior?**

you have the talend logo

### CODE REVIEW

**Comment by frassinier** [comment]
I don't think that our logo should be there?

**Comment by jsomsanith** [comment]
@frassinier can you explain why ?

**Comment by frassinier** [comment]
Talend icons try to be designed with square shape and I don't think this could done with this one. Do we really need logo as icon? I'm OK to merge but I wonder about its usage?

**Comment by jsomsanith** [comment]
`Talend icons try to be designed with square shape` --> You've got a point

**Pull request closed without merging**
