### PR TITLE
feat: add eye icon (for "read-only")

### PR DESCRIPTION
**Pull request by maximenicoul**
**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Docs have been added / updated

**What is the current behavior?** (You can also link to an open issue here)
no eye icon

**What is the new behavior?**
eye icon available

**This PR introduce breaking change**

**Other information**:

### CODE REVIEW

**Comment by jsomsanith** [comment]
Why is it small ?

**Comment by talend-glorieux** [comment]
Why use an eye instead of a blocked pencil?

**Comment by jsomsanith** [comment]
The eye is useful in TDP it is used to indicate that we are in preview mode (preview of the resulting data if a transformation is applied). Is that what you called `read-only` mode ?

**Comment by maximenicoul** [comment]
I know svg is meant to be rescaled but sometimes rescaling makes icons blurry, especially the small ones. That's why sometimes I prefer to make a small version to be pixel-perfect.

**Comment by jmfrancois** [comment]
Let's merge and if it lead to issues we will fix it

**Comment by maximenicoul** [comment]
The blocked pencil could have been a solution but the icon needed to be quite small, so it could look like a simple cross. The icon was meant to be used in TDS as a visual clue for read-only attributes in the grid, but it turns out we chose another solution, so it may not be useful anymore.

**Pull request merged**
